---
kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: incident-service-quarkus
      expose: "true"
    annotations:
    name: incident-service-quarkus
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      group: erd-services
      app: incident-service-quarkus
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: incident-service-quarkus
    name: incident-service-quarkus
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: incident-service-quarkus
      weight: 100
    wildcardPolicy: None
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: incident-service-quarkus
    name: incident-service-quarkus
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      group: erd-services
      app: incident-service-quarkus
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          group: erd-services
          app: incident-service-quarkus
      spec:
        containers:
          - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            imagePullPolicy: IfNotPresent
            name: incident-service-quarkus
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
              - containerPort: 9779
                name: prometheus
                protocol: TCP
              - containerPort: 8778
                name: jolokia
                protocol: TCP
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 3
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 3
              periodSeconds: 10
              timeoutSeconds: 3
            resources:
              limits:
                cpu: '100m'
                memory: '150Mi'
              requests:
                cpu: '50m'
                memory: '50Mi'
            securityContext:
              privileged: false
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /work/config
                name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: incident-service-quarkus
        serviceAccountName: incident-service-quarkus
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: incident-service-quarkus
            name: config
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - incident-service-quarkus
          from:
            kind: ImageStreamTag
            name: "incident-service-quarkus:0.0.1"
            namespace: openshift
        type: ImageChange